import { useTranslations } from '../../i18n/utils';

const t = useTranslations();

/** Optimized image data generated by the page via astro:assets `getImage`. */
export interface OptimizedImage {
  src: string;
  srcSet?: string;
}

interface Props {
  image: OptimizedImage;
}

export default function Hero({ image }: Props) {

  return (
    <section className="relative w-full overflow-hidden">
      <div className="relative h-screen w-full">
        {/* Background hyperlapse video (Dresden silhouette by twosyde media GmbH).
            The optimized image is the poster (shown while the video buffers and on
            devices that cannot play the source). */}
        <video
          className="absolute inset-0 h-full w-full object-cover object-center"
          autoPlay
          muted
          loop
          playsInline
          preload="auto"
          poster={image.src}
        >
          <source src="/dresden-hyperlapse.mp4" type="video/mp4" />
        </video>

        {/* Dark overlay */}
        <div className="absolute inset-0 bg-black/50" />

        {/* Video credit */}
        <div className="absolute bottom-4 right-4 text-[10px] uppercase tracking-[0.2em] text-white/60 z-10">
          Video · twosyde media GmbH
        </div>

        {/* Content */}
        <div className="relative h-full flex flex-col items-center justify-center px-6 text-center pt-16">
          <div className="max-w-5xl mx-auto animate-fade-up">
            <h1
              className="font-display text-7xl md:text-8xl lg:text-9xl font-extrabold text-white leading-[1] tracking-tight"
              style={{ textShadow: '0 4px 18px rgba(0,0,0,0.55)' }}
            >
              {t('hero.eventLabel')}
            </h1>

            <p
              className="mt-6 font-display text-2xl md:text-3xl lg:text-4xl font-bold text-white leading-[1.2]"
              style={{ textShadow: '0 2px 12px rgba(0,0,0,0.5)' }}
            >
              {t('hero.title').split('|').map((line, i, arr) => (
                <span key={i}>
                  {line}
                  {i < arr.length - 1 && <br />}
                </span>
              ))}
            </p>

            <p
              className="mt-5 text-white text-lg md:text-xl font-medium tracking-wide"
              style={{ textShadow: '0 1px 6px rgba(0,0,0,0.6)' }}
            >
              {t('hero.dates')}
            </p>

            {/* Non-clickable status pill — registration not yet open. */}
            <div
              className="mt-8 inline-flex items-center gap-2 px-6 py-3 rounded-full bg-white/15 backdrop-blur-sm border border-white/30 text-white font-medium text-sm uppercase tracking-[0.15em]"
              style={{ animationDelay: '0.2s', animationFillMode: 'both' }}
            >
              <span className="w-2 h-2 rounded-full bg-tu-gold motion-safe:animate-pulse" />
              {t('hero.cta')}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
